### ISSUE TITLE
Request for train dataset CSV File and Trainer.py Code Availability

### ISSUE THREAD

**Issue by ojwcv0315** [Pter61/context-i2w#12]
Could you please provide the CSV file used during training, where the parameter replaced_caption_key=args.csv_replace_key is passed? Additionally, I would like to know if the trainer.py code is going to be released soon. Thank you!

**Comment by Pter61** [comment]
Thank you for your interest in our work! 

The 'trainer.py' file and the data collection methodology will released soon.

The CSV file is unique to each one, depending on the order and content of the images you downloaded.

To process the CC3M dataset, you first need to confirm that the download type is in folder form. Here is the example of my download command: 
`img2dataset --url_list Train_GCC-training.tsv --input_format "tsv"\
         --url_col "url" --caption_col "caption" --output_format webdataset\
           --output_folder /tym/datasets/cc_3M/train/ --processes_count 16 --thread_count 64 --image_size 256\
             --enable_wandb True`

Then, you need to process the dataset into the input form required for training: [filepath, ...]. This is an example code of mine: 
        
        save_file_path = os.path.join(save_path, "Train_GCC-training_output.csv") 
        csv_list = []
        for root, dirs, files in tqdm(os.walk(data_path)):
            for file in files:
                if file[-4:] == ".jpg" and file[:2] != "._":
                    filepath, txt_file_path = os.path.join(root, file), os.path.join(root, file[:-4]+".txt")
                    title = read_txt_file(txt_file_path)
                    csv_list.append({"filepath":filepath, "title":title})
                    # print(img_path)
        print(len(csv_list))
        # save
        df = pd.DataFrame(csv_list, columns=["filepath", "title"])
        print(df)
        df.to_csv(save_file_path, index=False, sep="\t")

After that, apply spacy to replace the subjects to [REPLACE] token, where the csv_replace_key is ["filepath", 
"title", "title_replace"]:

        save_file_path = os.path.join(save_path, "Train_GCC-training_output.csv") if data_type == "train" \
            else os.path.join(save_path, "Validation_GCC-1.1.0-Validation_output.csv")

        csv_list = []

        for root, dirs, files in tqdm(os.walk(data_path)):
            for file in tqdm(files):
                if file[-4:] == ".jpg" and file[:2] != "._":
                    filepath, txt_file_path = os.path.join(root, file), os.path.join(root, file[:-4]+".txt")
                    title = read_txt_file(txt_file_path)
                    title_replace = get_replace_txt(title)
                    if title_replace == False:
                        continue
                    # print(title, "\t", title_replace)
                    csv_list.append({"filepath":filepath, "title":title, "title_replace":title_replace})


I will continue to update the complete processing and training steps after I finish my current work to contribute to the community. If you find it useful, feel free to Star my repo~
