### ISSUE TITLE
How to use CC3M for training?

### ISSUE THREAD

**Issue by flashingtt** [Pter61/context-i2w#2]
@Pter61 Thanks for your excellent work! I have some difficulties in utilizing the CC3M dataset.
Following the instructions in https://github.com/rom1504/img2dataset/blob/main/dataset_examples/cc3m.md, I downloaded the CC3M dataset with `*.parquet` `*.json` `*.tar` files.

I got a 500M .tsv file `Train_GCC-training.tsv`, while the training script needs a `Train_GCC-training_output.csv` file. I wonder the relationship between them.

Then I run the training code, getting error

> KeyError: 'filepath'

I reset the params in `params.py`: --csv-img-key url --csv-caption-key caption, and get error

> FileNotFoundError: [Errno 2] No such file or directory: 'https://ak7.picdn.net/shutterstock/videos/1392223/thumb/1.jpg'

This is my first time using these kinds of datasets, could you please share some experiences about how to utilize the CC3M dataset and which parts of the code should I change?

**Comment by Pter61** [comment]
@flashingtt  Thank you very much for your interest in my work!
To process the CC3M dataset, you first need to confirm that the download type is in folder form. Here is the example of my download command: XXX.
`img2dataset --url_list Train_GCC-training.tsv --input_format "tsv"\
         --url_col "url" --caption_col "caption" --output_format webdataset\
           --output_folder /tym/datasets/cc_3M/train/ --processes_count 16 --thread_count 64 --image_size 256\
             --enable_wandb True`
Then, you need to process the dataset into the input form required for training: [filepath, ...]. This is an example code of mine: 
        
        csv_list = []
        for root, dirs, files in tqdm(os.walk(data_path)):
            for file in files:
                if file[-4:] == ".jpg" and file[:2] != "._":
                    filepath, txt_file_path = os.path.join(root, file), os.path.join(root, file[:-4]+".txt")
                    title = read_txt_file(txt_file_path)
                    csv_list.append({"filepath":filepath, "title":title})
                    # print(img_path)
        # save
        df = pd.DataFrame(csv_list, columns=["filepath", "title"])
        df.to_csv(save_file_path, index=False, sep="\t")
        print("Saved to", save_file_path)

I will continue to update the complete processing and training steps after I finish my current work to contribute to the community. If you find it useful, feel free to Star my repo~

**Comment by flashingtt** [comment]
@Pter61 I've Starred your repo and thank you very much for your guidance. It worked! Now, I can successfully introduce the CC3M dataset during the training stage.

**Comment by flashingtt** [comment]
@Pter61 Hi, here I am again. I have one more question about the ImageNet dataset. I can download the imagenet-r data from the link https://github.com/hendrycks/imagenet-r, which includes two folders: imagenet-r and blurry_images. But the structure of the dataset shows that there is a folder named "real", it is a dataset for validation. I try to download the val_images of ImageNet from the huggingface, which contains 50000 images with a memory of 6.2GB. While the imgnet_real_query.txt shows the path of validation images should be the type of "imgnet/real/nxxxxxxxx/ILSVRC2012_val_xxxxxxxx.JPEG id". Now I only have 50000 images with the names "ILSVRC2012_val_xxxxxxxx.JPEG". I wonder how to get the "real" folder like the structure indicated.

**Comment by Pter61** [comment]
@flashingtt  Hi, I remember I downloaded it from this link: https://people.eecs.berkeley.edu/~hendrycks/blurry_images.tar, where under ImageNet-R's GitHub repository. Just change the file name to real.

I can’t remember clearly. If you have any questions, feel free to comment~

**Comment by Pter61** [comment]
@flashingtt I checked the notes of my implementation. At that time, I wrote a code to organize this data set. The function is as follows:

    def split_images(path, save_path):

        query_file_path = os.path.join(path, "imgnet_real_query.txt")
        img_path = os.path.join(path, "imgnet_val_2012")
    
        with open(query_file_path, "r") as f:
            query_lines = f.readlines()
        # print(type(txt))
        for query_line in tqdm(query_lines):
            # print(query_line.split(' ')[0].split('/'))
            img_folder, imgname = query_line.split(' ')[0].split('/')[2], query_line.split(' ')[0].split('/')[3]
            # print(img_folder, imgname)
            src_path = os.path.join(img_path, imgname)
            tgt_path = os.path.join(save_path, img_folder)
    
            assert os.path.isfile(src_path)
            check_folder_exist(tgt_path)
            shutil.copy(src_path, tgt_path)
            # print(src_path, "\n", tgt_path)

       print("Done!")

**Comment by flashingtt** [comment]
@Pter61 Ah, I see. The structure of my downloaded ImageNet validation set still differs from yours. But now I can organize them inspired by your code. Honestly speaking, I ignored the `split_real.py` in your repo and it's my fault. Thank you very much again~
