### ISSUE TITLE
Hi! I would like to ask whether the trainer file is not uploaded?

### ISSUE THREAD

**Issue by lz75258** [Pter61/context-i2w#3]
![xx](https://github.com/Pter61/context-i2w/assets/48471281/4ed1a935-6c9b-4a70-a2e4-471f50361d58)

**Comment by lz75258** [comment]
![xx](https://github.com/Pter61/context-i2w/assets/48471281/8d926c31-8176-4be0-8139-b75cb5a7c824)

**Comment by Pter61** [comment]
Yes, as I stated in my README, I have uploaded the checkpoint and inference code, which should be sufficient to support subsequent work for comparison and verification. I am now busy with an important task at hand. Once finished, I will upload and provide the complete data processing steps and training code to contribute to the community.

**Comment by lz75258** [comment]
Okay, thanks to the authors for this good work.
