### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Houwenjin** [Pter61/context-i2w#5]
Hi, very well done! When I wanted to try it, I found that I didn't have the "Train_GCC-training_output.csv" and "Validation_GCC-1.1.0-Validation_output.csv" files. Can you share it with me via Drive?

**Comment by Pter61** [comment]
These two files are based on the CC3M data set and need to be downloaded and generated by individuals (because the file paths inside are different for everyone).

**Comment by Pter61** [comment]
Of course, that is a very simple function:
`def read_txt_file(path):
    with open(path, "r") as f:
        txt = f.read()
    return txt`
