### ISSUE TITLE
[Q]difference between the "cirr" option and the "cirr_test" option in the eval settings

### ISSUE THREAD

**Issue by YuetianW** [Pter61/context-i2w#6]
Hello, I would like to ask what is the difference between the "cirr" option and the "cirr_test" option in the eval settings?
Thanks again for your excellent work!💕

**Comment by Pter61** [comment]
Thank you for your interest in my work! CIRR is tested on offline validation data, while CIRR_test outputs the test results and sends them to the online test on the CIRR benchmark for verification. The results reported in our paper are the results of CIRR_test.

**Comment by YuetianW** [comment]
Got it! 
Thanks for your reply.✨
